media:
  input: assets/images
  output: /assets/images

content:
  - name: home
    label: Home
    type: file
    path: _data/home.yml
    fields:
      - name: hero_title
        label: Hero Title
        type: string
      - name: hero_body
        label: Hero Body
        type: text
      - name: callouts
        label: Callouts
        type: object
        list: true
        fields:
          - name: title
            label: Title
            type: string
          - name: body
            label: Body
            type: text
      - name: showcase_title
        label: Showcase Title
        type: string
      - name: showcase_body
        label: Showcase Body
        type: text
      - name: showcase_image
        label: Showcase Image
        type: string

  - name: posts
    label: Blog Posts
    type: collection
    path: _posts
    view:
      fields: [title, date, author]
      primary: title
      sort: [date, desc]
    fields:
      - name: title
        label: Title
        type: string
      - name: date
        label: Date
        type: date
      - name: author
        label: Author
        type: string
      - name: categories
        label: Categories
        type: string
        list: true
      - name: excerpt
        label: Excerpt
        type: text
      - name: body
        label: Body
        type: rich-text
